import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import styles from './Layout.module.scss'

const Layout = ({ children }) => {
  const [openMenu, setOpenMenu] = useState(false)
  const [id, setId] = useState(1)
  const { pathname } = useRouter()
  useEffect(() => {
    if (pathname === '/about') setId(2)
    if (pathname === '/projects') setId(3)
    if (pathname === '/contact') setId(4)
  }, [pathname])
  return (
    <>
      <Head>
        <title>Mike Smith Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css'
          integrity='sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=='
          crossOrigin='anonymous'
          referrerPolicy='no-referrer'
        />
      </Head>
      <header>
        <div className={styles.menuBtn} onClick={() => setOpenMenu(!openMenu)}>
          <span
            className={
              !openMenu
                ? styles.menuBtn__burger
                : `${styles.menuBtn__burger} ${styles.open}`
            }></span>
        </div>

        <nav
          className={!openMenu ? styles.nav : `${styles.nav} ${styles.open}`}>
          <ul
            className={
              !openMenu ? styles.menuNav : `${styles.menuNav} ${styles.open}`
            }>
            <li
              className={
                !openMenu
                  ? styles.menuNav__item
                  : `${styles.menuNav__item} ${styles.open}`
              }>
              <a
                href='/'
                className={
                  id === 1
                    ? `${styles.menuNav__link} ${styles.active}`
                    : styles.menuNav__link
                }>
                Home
              </a>
            </li>
            <li
              className={
                !openMenu
                  ? styles.menuNav__item
                  : `${styles.menuNav__item} ${styles.open}`
              }>
              <a
                href='/about'
                className={
                  id === 2
                    ? `${styles.menuNav__link} ${styles.active}`
                    : styles.menuNav__link
                }>
                About Me
              </a>
            </li>
            <li
              className={
                !openMenu
                  ? styles.menuNav__item
                  : `${styles.menuNav__item} ${styles.open}`
              }>
              <a
                href='/projects'
                className={
                  id === 3
                    ? `${styles.menuNav__link} ${styles.active}`
                    : styles.menuNav__link
                }>
                My Projects
              </a>
            </li>
            <li
              className={
                !openMenu
                  ? styles.menuNav__item
                  : `${styles.menuNav__item} ${styles.open}`
              }>
              <a
                href='/contact'
                className={
                  id === 4
                    ? `${styles.menuNav__link} ${styles.active}`
                    : styles.menuNav__link
                }>
                Contact Me
              </a>
            </li>
          </ul>
        </nav>
      </header>
      <main>{children}</main>
    </>
  )
}

export default Layout
